version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scry_dummy_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_DATABASE=scry_pg_db
      - DB_USERNAME=scry_user
      - DB_PASSWORD=secret_password
      - DB_MYSQL_HOST=mysql
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_DATABASE=scry_my_db
      - DB_MYSQL_USERNAME=scry_user
      - DB_MYSQL_PASSWORD=secret_password
    depends_on:
      - pgsql
      - mysql
    networks:
      - scry_network

  pgsql:
    image: postgres:16
    container_name: scry_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: scry_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: scry_pg_db
    volumes:
      - scry_pg_data:/var/lib/postgresql/data
    networks:
      - scry_network

  mysql:
    image: mysql:8.0
    container_name: scry_mysql
    environment:
      MYSQL_USER: scry_user
      MYSQL_PASSWORD: secret_password
      MYSQL_DATABASE: scry_my_db
      MYSQL_ROOT_PASSWORD: secret_root_password
    ports:
      - "3306:3306"
    volumes:
      - scry_my_data:/var/lib/mysql
    networks:
      - scry_network

volumes:
  scry_pg_data:
  scry_my_data:

networks:
  scry_network:
    driver: bridge
