version: '3.8'

services:
  pgsql:
    image: postgres:16
    container_name: scry_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: scry_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: scry_pg_db
    volumes:
      - scry_pg_data:/var/lib/postgresql/data
    networks:
      - scry_network

  mysql:
    image: mysql:8.0
    container_name: scry_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: scry_user
      MYSQL_PASSWORD: secret_password
      MYSQL_DATABASE: scry_my_db
      MYSQL_ROOT_PASSWORD: secret_root_password
    volumes:
      - scry_my_data:/var/lib/mysql
    networks:
      - scry_network

  mariadb:
    image: mariadb:10.11
    container_name: scry_mariadb
    ports:
      - "3307:3306"
    environment:
      MARIADB_USER: scry_user
      MARIADB_PASSWORD: secret_password
      MARIADB_DATABASE: scry_maria_db
      MARIADB_ROOT_PASSWORD: secret_root_password
    volumes:
      - scry_maria_data:/var/lib/mysql
    networks:
      - scry_network

  sqlsrv:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: scry_sqlsrv
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Secret_Password123!"
    volumes:
      - scry_sql_data:/var/opt/mssql
    networks:
      - scry_network

volumes:
  scry_pg_data:
  scry_my_data:
  scry_maria_data:
  scry_sql_data:

networks:
  scry_network:
    driver: bridge
